### PR TITLE
Fix/current reverted

### PR DESCRIPTION
**Pull request by zjesko**

### CODE REVIEW

**Comment by jessepinkman9900** [comment]
Looks like you converted a contract call into `try_` call. This change looks good. 
Would you have to make this for the forte swap subgraph as well?

**Comment by zjesko** [comment]
yeah, handled the contract call being reverted. Change is already made in forteswap (its actually inspired from there)

**Comment by zjesko** [comment]
@jessepinkman9900 @SiddarthVijay please mark it as reviewed if it looks good

**Review by jessepinkman9900 — APPROVED** [review]

**Review by 0xtemujin — COMMENTED** [review]
LGTM!

**Review by 0xtemujin — APPROVED** [review]
LGTM

**Pull request merged**
